#!/bin/sh

set -e

if [ -z "$1" -o -z "$2" ]; then
  echo "Usage: scripts/build-and-tar-host VERSION PLATFORM"
  echo "E.g. scripts/build-and-tar-host 0.1.0 x86_64-apple-darwin"
  exit 1
fi

VERSION="$1"
PLATFORM="$2"

cargo build --release
strip "target/release/titlecase"
tar zcf "target/titlecase-${VERSION}-${PLATFORM}.tar.gz" -C "target/release" titlecase
