#!/bin/sh

set -e

mkdir -p target/x86_64-unknown-freebsd/release

# NOTE: Assumes there is a .cargo/config present that sets the linker
# appropriately for the x86_64-unknown-freebsd target:
#
# [target.x86_64-unknown-freebsd]
# linker = "x86_64-pc-freebsd12-gcc"

# Build
docker run --rm -it \
  -v "$(pwd)":/home/rust/code:ro \
  -v titlecase-freebsd-target:/home/rust/code/target \
  -v titlecase-freebsd-cargo-registry:/home/rust/.cargo/registry \
  freebsd-cross-rust build --release --target x86_64-unknown-freebsd

# Copy binary out of volume into target/x86_64-unknown-freebsd
docker run --rm -it \
  -v "$(pwd)"/target/x86_64-unknown-freebsd/release:/home/rust/output \
  -v titlecase-freebsd-target:/home/rust/code/target \
  --entrypoint cp \
  freebsd-cross-rust \
  /home/rust/code/target/x86_64-unknown-freebsd/release/titlecase /home/rust/output
